name: Send notification on push
on:
  schedule:
    - cron: "0 1,4,10,11 * * *"

jobs:
  send-msg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # 纯文本类型
      - name: WeChat Work notification by text
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: text
          content: "填写TS了，每天9点，12点，18点提醒！"
          mentioned_list: '["@all"]'
